# Generated by Django 3.0.5 on 2020-09-23 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SNL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.SlugField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('started', models.BooleanField(default=True)),
                ('max_player', models.IntegerField(default=0)),
                ('current', models.IntegerField(default=0)),
                ('winner_state', models.IntegerField(default=0)),
                ('player_intered', models.IntegerField(default=0)),
                ('current_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Room')),
            ],
        ),
        migrations.CreateModel(
            name='SNLPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('color', models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN')], default='', max_length=10)),
                ('ready', models.BooleanField(default=False)),
                ('left', models.IntegerField(default=0)),
                ('bottom', models.IntegerField(default=0)),
                ('disable', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=1)),
                ('can_move', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snakeAndLadder.SNL')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SNLMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snakeAndLadder.SNL')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snakeAndLadder.SNLPlayer')),
            ],
        ),
    ]
