# Generated by Django 3.1.3 on 2020-12-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakeAndLadder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snl',
            name='last_check',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
