# Generated by Django 3.0.5 on 2020-09-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakeAndLadder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snl',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
