# Generated by Django 3.0.5 on 2020-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakeAndLadder', '0002_auto_20200923_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snl',
            old_name='player_intered',
            new_name='player_entered',
        ),
        migrations.AddField(
            model_name='snl',
            name='time_stamp',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snlplayer',
            name='entered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snlplayer',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
