# Generated by Django 3.0.5 on 2020-09-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakeAndLadder', '0003_auto_20200923_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snl',
            name='time_stamp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
