# Generated by Django 3.0.5 on 2020-09-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakeAndLadder', '0004_auto_20200923_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snl',
            name='current',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
