# Generated by Django 3.0.5 on 2020-09-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakeAndLadder', '0006_snlplayer_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snlplayer',
            name='round',
        ),
        migrations.AddField(
            model_name='snl',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
