# Generated by Django 3.0.5 on 2020-10-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snakeAndLadder', '0007_auto_20200926_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snl',
            name='date',
        ),
        migrations.RemoveField(
            model_name='snl',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='snl',
            name='time',
        ),
        migrations.RemoveField(
            model_name='snl',
            name='winner',
        ),
    ]
