# Generated by Django 3.0.5 on 2020-10-04 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snakeAndLadder', '0009_auto_20201002_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snlplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snl_player', to='snakeAndLadder.SNL'),
        ),
    ]
