# Generated by Django 3.0.5 on 2020-10-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakeAndLadder', '0010_auto_20201004_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='snl',
            name='player_disabled',
            field=models.IntegerField(default=0),
        ),
    ]
