# Generated by Django 3.0.5 on 2020-10-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakeAndLadder', '0011_snl_player_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snlplayer',
            name='bottom',
        ),
        migrations.RemoveField(
            model_name='snlplayer',
            name='left',
        ),
        migrations.AlterField(
            model_name='snlplayer',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
