# Generated by Django 3.0.5 on 2020-10-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snakeAndLadder', '0013_auto_20201013_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snlmessage',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='snakeAndLadder.SNL'),
        ),
    ]
