# Generated by Django 3.0.5 on 2020-10-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201001_2155'),
        ('snakeAndLadder', '0014_auto_20201013_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='snlplayer',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Member'),
        ),
    ]
