# Generated by Django 3.0.5 on 2020-10-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snakeAndLadder', '0015_snlplayer_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='snl',
            name='players_playing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snlplayer',
            name='leaved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='snlplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='snakeAndLadder.SNL'),
        ),
    ]
