# Generated by Django 3.0.5 on 2020-10-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snakeAndLadder', '0016_auto_20201015_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snl',
            old_name='player_disabled',
            new_name='players_disabled',
        ),
        migrations.RenameField(
            model_name='snl',
            old_name='player_entered',
            new_name='players_entered',
        ),
        migrations.RemoveField(
            model_name='snlplayer',
            name='ready',
        ),
    ]
