# Generated by Django 3.1.3 on 2021-03-04 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2021, 3, 4, 10, 19, 13, 511736, tzinfo=utc)),
        ),
    ]
