# Generated by Django 3.1.3 on 2021-03-07 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210304_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
