# Generated by Django 3.0.5 on 2020-11-04 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticTacToe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tac',
            name='cross_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tac',
            name='cross_entered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tac',
            name='winning_chances',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='tac',
            name='zero_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tac',
            name='zero_entered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tac',
            name='board',
            field=jsonfield.fields.JSONField(default=[[0, 0, 0], [0, 0, 0], [0, 0, 0]]),
        ),
        migrations.CreateModel(
            name='TACMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='ticTacToe.TAC')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
