# Generated by Django 3.1.3 on 2020-12-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=150)),
                ('host', models.BooleanField()),
            ],
            options={
                'unique_together': {('msg', 'host')},
            },
        ),
    ]
