# Generated by Django 3.0.5 on 2020-10-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201001_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='leaved',
            field=models.BooleanField(default=False),
        ),
    ]
