# Generated by Django 3.0.5 on 2020-10-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='sp_id',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
    ]
